language: android
android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-22.0.1
    - android-22

    # Support library
    - extra-android-support
    - extra-android-m2repository

script:
    - chmod +x ./gradlew
